# Generated by Django 4.0.4 on 2022-05-27 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='images')),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
